### PR TITLE
Replace ts() with E::ts()

### PR DESCRIPTION
**Pull request by lucky091588**

### CODE REVIEW

**Comment by lucky091588** [comment]
I need help testing the changes since I don't know where to check it on the browser.

**Comment by twomice** [comment]
When the extension is enabled, visit any event configuration page (e.g. https://example.l/civicrm/event/manage/settings?reset=1&action=update&id=3) and you should see a tab labeled  'Participant Letter'. That tab's title is the translated text from line 12 in this PR. @lucky091588

**Comment by lucky091588** [comment]
@twomice I already check this and there is not E error.

**Comment by twomice** [comment]
Merged, thanks @lucky091588

**Pull request merged**
